name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Build the Prepare Docker image
      run: docker build . --file Dockerfile --tag pyramid-read-ea
    - name: test
      run: docker run -v "$(pwd)/data:/data" pyramid-read-ea
